### ISSUE TITLE
Create static text

### ISSUE THREAD

**Issue by caseyclement** [bigjosh/MacroMarquee#3]
New to the coding world - Trying to figure out how to make a simple static text across my display. Working on making a subway sign that links into the public transit database for a school project. Thanks!

**Comment by bigjosh** [comment]
You have come to the right repo! Check out this sketch that does just that...

https://github.com/bigjosh/MacroMarquee/blob/master/Arduino/SimpleScroll/SimpleScroll.ino

Check out the readme for more info and links to the articles on how to build a sign.
