### ISSUE TITLE
More pins for taller fonts

### ISSUE THREAD

**Issue by dallen98** [bigjosh/MacroMarquee#4]
Can the ticker work on esp32, arduino due ? or is it just confined to mega/uno ??

**Comment by bigjosh** [comment]
This code is specifically for AVR-based processors. 

ESP32 and Arduino Due are completely different beasts, so completely different code would be required.

https://wp.josh.com/2016/05/20/huge-scrolling-arduino-led-sign/#more-4623:~:text=Q%3A%20Will%20this%20run%20on%20on%20other%20boards%20besides%20Arduino%20Uno%3F

**Comment by bigjosh** [comment]
You could do fonts up to about 14 rows tall on an AVR Arduino like an UNO.

**Comment by dallen98** [comment]
would this zigzag code work to achieve taller fonts ? Thanks

#include <FastLED.h>        //https://github.com/FastLED/FastLED
#include <LEDMatrix.h>      //https://github.com/Jorgen-VikingGod/LEDMatrix

// Change the next defines to match your matrix type and size
#define DATA_PIN            14

#define COLOR_ORDER         GRB
#define CHIPSET             WS2812B

// initial matrix layout (to get led strip index by x/y)
#define MATRIX_WIDTH        11
#define MATRIX_HEIGHT       11
#define MATRIX_TYPE         HORIZONTAL_ZIGZAG_MATRIX
#define MATRIX_SIZE         (MATRIX_WIDTH*MATRIX_HEIGHT)
#define NUMPIXELS           MATRIX_SIZE

// create our matrix based on matrix definition
cLEDMatrix<MATRIX_WIDTH, MATRIX_HEIGHT, MATRIX_TYPE> leds;
